### ISSUE TITLE
MethodError: no method matching render(::Atom.Console, ::Int64; options=Dict{Any,Any}())

### ISSUE THREAD

**Issue by elanmart** [JunoLab/uber-juno#11]
Hi, 

I've been working with Julia 0.5 recently and wanted to try out Juno as well. 
After following the instructions, I've managed to get rid of all compilation errors. I get the message that Atom (Juno?) successfully launched Julia.
However, when I try to evaluate anything in Console (say `x = 1`) I get an error:
```
MethodError: no method matching render(::Atom.Console, ::Int64; options=Dict{Any,Any}())

Closest candidates are:
  render(::Atom.Console, ::Any) got an unsupported keyword argument "options"
  render(!Matched::Atom.Editor, ::Any) got an unsupported keyword argument "options"
  render(::Atom.Console, !Matched::Void) got an unsupported keyword argument "options"
  ...
 in yieldto(::Task, ::ANY) at ./event.jl:89
 in wait() at ./event.jl:122
 in wait(::Condition) at ./event.jl:17
 in (::Atom.##122#126)(::Dict{String,Any}) at /home/elan/.julia/v0.5/Atom/src/eval.jl:103
 in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at /home/elan/.julia/v0.5/Atom/src/comm.jl:71
 in (::Atom.##5#8)() at ./event.jl:46
```

When I evaluate the same `x=1` in the main window, I get red box with the following:
```
MethodError: no method matching similar(::Dict{Any,Any}, ::Type{String})
Closest candidates are:
  similar(!Matched::SubArray{T,N,P,I,L}, ::Type{T}, !Matched::Tuple{Vararg{Int64,N}})
  similar{T}(!Matched::Array{T,1}, ::Type{T})
  similar{T}(!Matched::Array{T,2}, ::Type{T})
  ...
 in _collect(::Dict{Any,Any}, ::Base.Generator{Dict{Any,Any},Hiccup.##7#8}, ::Base.EltypeUnknown, ::Base.HasLength) at ./array.jl:285
 in attrstring at /home/elan/.julia/v0.5/Hiccup/src/Hiccup.jl:54 [inlined]
 in render(::IOContext{Base.AbstractIOBuffer{Array{UInt8,1}}}, ::Hiccup.Node{:span}) at /home/elan/.julia/v0.5/Hiccup/src/Hiccup.jl:63
 in verbose_show(::Base.AbstractIOBuffer{Array{UInt8,1}}, ::MIME{Symbol("text/plain")}, ::Hiccup.Node{:span}) at ./multimedia.jl:50
 in #sprint#221(::Void, ::Function, ::Int64, ::Function, ::MIME{Symbol("text/plain")}, ::Vararg{Any,N}) at ./strings/io.jl:37
 in stringmime(::MIME{Symbol("text/plain")}, ::Hiccup.Node{:span}) at ./multimedia.jl:65
 in macro expansion at /home/elan/.julia/v0.5/Atom/src/display/objects.jl:18 [inlined]
 in #render#61(::Dict{Any,Any}, ::Function, ::Atom.Inline, ::Hiccup.Node{:span}) at /home/elan/.julia/v0.5/Media/src/system.jl:165
 in (::Media.#kw##render)(::Array{Any,1}, ::Media.#render, ::Atom.Inline, ::Hiccup.Node{:span}) at ./<missing>:0
 in render(::Atom.Inline, ::Int64) at /home/elan/.julia/v0.5/Media/src/system.jl:165
 in render at /home/elan/.julia/v0.5/Atom/src/display/view.jl:81 [inlined]
 in render(::Atom.Editor, ::Int64) at /home/elan/.julia/v0.5/Atom/src/display/display.jl:23
 in (::Atom.##106#110)(::Dict{String,Any}) at /home/elan/.julia/v0.5/Atom/src/eval.jl:62
 in handlemsg(::Dict{String,Any}, ::Dict{String,Any}, ::Vararg{Dict{String,Any},N}) at /home/elan/.julia/v0.5/Atom/src/comm.jl:71
 in (::Atom.##5#8)() at ./event.jl:46
```

I'm using 2-days old Julia and newest Atom.jl and CodeTools.jl

**Comment by MikeInnes** [comment]
Since Juno doesn't have official support on 0.5 yet it might take a couple more checkouts to get this working. Checking out MacroTools, Requires and and Media will probably do the job.

**Comment by MikeInnes** [comment]
This should be fixed now (and everything should work on the latest tag) but let me know if you're still having an issue.
